services:
  kali-gui:
    image: kalilinux/kali-rolling
    container_name: kali-gui
    ports:
      - "6080:6080" # noVNC-Port für Browser-Zugriff
    tty: true
    stdin_open: true
    command: /bin/bash -c "
      apt-get update && apt-get install -y \
        xfce4 xfce4-goodies tightvncserver dbus-x11 \
        x11-xserver-utils xfonts-base wget novnc websockify \
        kali-linux-default \
      && mkdir -p ~/.vnc \
      && echo 'root' | vncpasswd -f > ~/.vnc/passwd \
      && chmod 600 ~/.vnc/passwd \
      && export USER=root \
      && vncserver :1 -geometry 1280x800 -depth 24 \
      && websockify --web=/usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5901"
