services:
  kali-gui:
    image: kalilinux/kali-rolling
    container_name: kali-gui
    ports:
      - "6080:6080"  # Zugriff im Browser über http://localhost:6080
    environment:
      - USER=root
      - PASSWORD=toor
    tty: true
    restart: unless-stopped
    command: >
      bash -c "
        apt update &&
        DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xfce4-goodies tightvncserver novnc websockify &&
        mkdir -p ~/.vnc &&
        echo toor | vncpasswd -f > ~/.vnc/passwd &&
        chmod 600 ~/.vnc/passwd &&
        export DISPLAY=:1 &&
        vncserver :1 -geometry 1280x800 -depth 24 &&
        websockify --web=/usr/share/novnc/ 6080 localhost:5901
      "
