version: "3"

services:
  kali:
    image: tigros/kali-desktop-xfce-vnc
    container_name: kali-gui
    ports:
      - "6080:6080"
    environment:
      - VNC_PASSWORD=kali
    restart: unless-stopped
